### ISSUE TITLE
Unhandled Exception: PlatformException(Failed, Failed to discover services, null, null)

### ISSUE THREAD

**Issue by konsultaner** [Navideck/universal_ble#71]
I get an exception when trying to register a characteristik on android (11 and 14) using the latest flutter version. It does work when compiling it to linux.

```
Unhandled Exception: PlatformException(Failed, Failed to discover services, null, null)
```

This is my demo app code:

```dart
void initState() {
    super.initState();
    _startScan();
  }

  Future<void> _startScan() async {
    AvailabilityState state = await UniversalBle.getBluetoothAvailabilityState();
    if (state != AvailabilityState.poweredOn) {
      return;
    }

    await UniversalBle.stopScan();

    UniversalBle.onScanResult = (BleDevice device) async {
      if (device.name == 'AdaESP32') {
        await UniversalBle.stopScan();
///////////////
/// I debounced it because this would be called up to 4 times in parallel. I thought this might fix this error but it didn't
/////////////////////
        _debounceConnectToDevice(device);
      }
    };

    await UniversalBle.startScan();
  }

  void _debounceConnectToDevice(BleDevice device, {Duration debounceDuration = const Duration(milliseconds: 300)}) {
    // Cancel the existing timer if it exists
    if (_debounceTimer?.isActive ?? false) {
      _debounceTimer!.cancel();
    }

    // Set up a new timer to call the connect function after the debounce duration
    _debounceTimer = Timer(debounceDuration, () => _connectToDevice(device));
  }

  Future<void> _connectToDevice(BleDevice device) async {
    _device = device;
    BleConnectionState connectionState = await _device.connectionState;
    if (connectionState == BleConnectionState.disconnected) {
      await UniversalBle.connect(_device.deviceId);
      await _discoverServices(_device.deviceId);
    } else if (connectionState == BleConnectionState.connected) {
      await _discoverServices(_device.deviceId);
    }
  }

  Future<void> _discoverServices(String deviceId) async {
    List<BleService> services = await UniversalBle.discoverServices(deviceId);
    UniversalBle.onValueChange = (String deviceId, String characteristicId, Uint8List value) {
      if (characteristicId == _characteristicUuid) {
        Uint8List newJsonBuffer = Uint8List(_jsonBuffer.length + value.length);
        newJsonBuffer.setAll(0, _jsonBuffer);
        newJsonBuffer.setAll(_jsonBuffer.length,value);
        if (newJsonBuffer.isNotEmpty && newJsonBuffer.last == 0x00) {
          _jsonBuffer = Uint8List(0);
          _handleData(newJsonBuffer);
        } else {
          _jsonBuffer = newJsonBuffer;
        }
      }
    };

    services.forEach((service) {
      if (service.uuid == serviceUuid) {
        Iterable<BleCharacteristic> characteristics = service.characteristics.where((characteristic) => characteristic.uuid == _characteristicUuid);
        if (characteristics.isNotEmpty) {
          BleCharacteristic characteristic = characteristics.first;
//////////////////////////////////////
// THIS IS WERE I GET THE ERROR
//////////////////////////////////////
          UniversalBle.setNotifiable(deviceId, service.uuid, characteristic.uuid, BleInputProperty.notification);
        }
      }
    },);
  }
```

This is some debug output:

```shell
I/BLASTBufferQueue(23653): [SurfaceView[com.example.app/com.example.app.MainActivity]@0#1](f:0,a:0,s:0) onFrameAvailable the first frame is available
D/SurfaceView@14eff90(23653): 21954448 setAlpha: alpha=1.0
I/SurfaceView(23653): 21954448 Changes: creating=false format=false size=false visible=false alpha=true hint=false visible=false left=false top=false z=false attached=true lifecycleStrategy=false
I/SurfaceView@14eff90(23653): 21954448 Cur surface: Surface(name=null)/@0x516c57f
I/SurfaceView@14eff90(23653): updateSurface: mVisible = true mSurface.isValid() = true
I/SurfaceView@14eff90(23653): updateSurface: mSurfaceCreated = true surfaceChanged = false visibleChanged = false
I/SurfaceView(23653): 21954448 surfaceRedrawNeeded
I/SurfaceView(23653): 21954448 finishedDrawing
V/SurfaceView@14eff90(23653): Layout: x=0 y=0 w=1768 h=2082, frame=Rect(0, 0 - 1768, 2082)
I/ViewRootImpl@ec5313e[MainActivity](23653): Setup new sync=wmsSync-ViewRootImpl@ec5313e[MainActivity]#2
I/ViewRootImpl@ec5313e[MainActivity](23653): Creating new active sync group ViewRootImpl@ec5313e[MainActivity]#3
I/ViewRootImpl@ec5313e[MainActivity](23653): registerCallbacksForSync syncBuffer=false
D/SurfaceView(23653): 21954448 updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 1768, 2082] surfaceSize = 1768x2082
I/SurfaceView@14eff90(23653): uSP: rtp = Rect(0, 0 - 1768, 2082) rtsw = 1768 rtsh = 2082
I/SurfaceView@14eff90(23653): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@14eff90(23653): aOrMT: ViewRootImpl@ec5313e[MainActivity] t = android.view.SurfaceControl$Transaction@61b25e4 fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:369 
I/ViewRootImpl@ec5313e[MainActivity](23653): mWNT: t=0xb400007b59405f90 mBlastBufferQueue=0xb400007b793e3ed0 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.SurfaceView.applyOrMergeTransaction:1598 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 
I/ViewRootImpl@ec5313e[MainActivity](23653): Received frameDrawingCallback syncResult=0 frameNum=1.
I/ViewRootImpl@ec5313e[MainActivity](23653): mWNT: t=0xb400007b59404150 mBlastBufferQueue=0xb400007b793e3ed0 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13841 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack> 
I/ViewRootImpl@ec5313e[MainActivity](23653): Setting up sync and frameCommitCallback
I/BLASTBufferQueue(23653): [ViewRootImpl@ec5313e[MainActivity]#0](f:0,a:0,s:0) onFrameAvailable the first frame is available
I/ViewRootImpl@ec5313e[MainActivity](23653): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
D/OpenGLRenderer(23653): CFMS:: SetUp Pid : 23653    Tid : 23681
I/ViewRootImpl@ec5313e[MainActivity](23653): reportDrawFinished seqId=0
I/ViewRootImpl@ec5313e[MainActivity](23653): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/ViewRootImpl@ec5313e[MainActivity](23653): handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
D/ViewRootImpl@ec5313e[MainActivity](23653): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007b694147c0}
D/InputMethodManagerUtils(23653): startInputInner - Id : 0
I/InputMethodManager(23653): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
D/InputMethodManagerUtils(23653): startInputInner - Id : 0
I/InsetsController(23653): onStateChanged: host=com.example.app/com.example.app.MainActivity, from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:7209, state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1768, 2208), mDisplayCutout=DisplayCutout{insets=Rect(0, 0 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=0 displayHeight=0 physicalDisplayWidth=0 physicalDisplayHeight=0 density={0.0} cutoutSpec={} rotation={0} scale={0.0} physicalPixelDisplaySizeRatio={0.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=53, center=Point(53, 53)}, RoundedCorner{position=TopRight, radius=53, center=Point(1715, 53)}, RoundedCorner{position=BottomRight, radius=53, center=Point(1715, 2155)}, RoundedCorner{position=BottomLeft, radius=53, center=Point(53, 2155)}]}  mRoundedCornerFrame=Rect(0, 0 - 1768, 2208), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(1652, 0 - 1768, 88) rotation=0}, mDisplayShape=DisplayShape{ spec=-311912193 displayWidth=1768 displayHeight=2208 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {cf980000 mType=statusBars mFrame=[0,0][1768,88] mVisible=true mFlags=[]}, InsetsSource: {cf980005 mType=mandatorySystemGestures mFrame=[0,0][1768,88] mVisible=true mFlags=[]}, InsetsSource: {cf980006 mType=tappableElement mFrame=[0,0][1768,88] mVisible=true mFlags=[]}, InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {479d0004 mType=systemGestures mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {479d0005 mType=mandatorySystemGestures mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {479d0006 mType=tappableElement mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {479d0024 mType=systemGestures mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {668b0001 mType=navigationBars mFrame=[0,2082][1768,2208] mVisible=true mFlags=[]}, InsetsSource: {668b0004 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {668b0005 mType=mandatorySystemGestures mFrame=[0,2082][1768,2208] mVisible=true mFlags=[]}, InsetsSource: {668b0006 mType=tappableElement mFrame=[0,2082][1768,2208] mVisible=true mFlags=[]}, InsetsSource: {668b0024 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]} }
I/InsetsSourceConsumer(23653): applyRequestedVisibilityToControl: visible=false, type=ime, host=com.example.app/com.example.app.MainActivity
I/ViewRootImpl@ec5313e[MainActivity](23653): onDisplayChanged oldDisplayState=2 newDisplayState=2
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
I/BluetoothAdapter(23653): BLE support array set: [true, true, true, true, true, true, true]
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothLeScanner(23653): could not find callback wrapper
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothAdapter(23653): semIsBleEnabled(): ON
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothLeScanner(23653): Start Scan with callback
D/BluetoothLeScanner(23653): onScannerRegistered() - status=0 scannerId=9 mScannerId=0
I/BluetoothAdapter(23653): BluetoothAdapter() : com.example.app
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothLeScanner(23653): Stop Scan with callback
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/BluetoothLeScanner(23653): could not find callback wrapper
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
D/CompatibilityChangeReporter(23653): Compat change id reported: 265103382; UID 10571; state: ENABLED
D/BluetoothGatt(23653): connect() - device: XX:XX:XX:XX:A3:0A, auto: false
D/BluetoothGatt(23653): registerApp()
D/BluetoothGatt(23653): registerApp() - UUID=3b9525f7-c006-400f-ad13-0dada2cf7a46
D/BluetoothGatt(23653): onClientRegistered() - status=0 clientIf=6
D/BluetoothGatt(23653): discoverServices() - device: XX:XX:XX:XX:A3:0A
D/BluetoothAdapter(23653): getBleEnabledArray(): ON
E/flutter (23653): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Failed, Failed to discover services, null, null)
E/flutter (23653): #0      UniversalBlePlatformChannel.discoverServices (package:universal_ble/src/universal_ble_pigeon/universal_ble.g.dart:446:7)
E/flutter (23653): <asynchronous suspension>
E/flutter (23653): #1      UniversalBlePigeonChannel.discoverServices (package:universal_ble/src/universal_ble_pigeon/universal_ble_pigeon_channel.dart:59:9)
E/flutter (23653): <asynchronous suspension>
E/flutter (23653): #2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949:15)
E/flutter (23653): <asynchronous suspension>
E/flutter (23653): #3      _QueuedFuture.execute (package:universal_ble/src/queue.dart:65:18)
E/flutter (23653): <asynchronous suspension>
E/flutter (23653): 
D/BluetoothGatt(23653): onClientConnectionState() - status=0 clientIf=6 device=XX:XX:XX:XX:A3:0A
D/UniversalBlePlugin(23653): onConnectionStateChange-> Status: 0, NewState: 2
D/BluetoothGatt(23653): onConnectionUpdated() - Device=XX:XX:XX:XX:A3:0A interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(23653): onConnectionUpdated() - Device=XX:XX:XX:XX:A3:0A interval=36 latency=0 timeout=500 status=0
I/ViewRootImpl@ec5313e[MainActivity](23653): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/ViewRootImpl@ec5313e[MainActivity](23653): onDisplayChanged oldDisplayState=2 newDisplayState=2
I/ViewRootImpl@ec5313e[MainActivity](23653): handleAppVisibility mAppVisible = true visible = false
I/ViewRootImpl@ec5313e[MainActivity](23653): stopped(true) old = false
D/ViewRootImpl@ec5313e[MainActivity](23653): WindowStopped on com.example.app/com.example.app.MainActivity set to true
D/OpenGLRenderer(23653): CacheManager::trimMemory(20)
```

This is my flutter version output:

```shell
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (vor 3 Wochen) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
```

**Comment by rohitsangwan01** [comment]
@konsultaner you have to wait for connection first

```dart
await UniversalBle.connect(_device.deviceId);
await _discoverServices(_device.deviceId);
```

here when call connect method, you have to wait for connection update callback in `onConnectionChange`

```dart
UniversalBle.onConnectionChange = (String deviceId, bool isConnected) {
  debugPrint('OnConnectionChange $deviceId, $isConnected');
  // Here you can discover services if connected
}
```

**Comment by rohitsangwan01** [comment]
@konsultaner is example app working fine for you ?

**Comment by konsultaner** [comment]
> @konsultaner is example app working fine for you?

No, I have to [activly request for permission](https://github.com/Navideck/universal_ble/blob/5ce6c3d3627fc59fa31bafb35f61ad916a09627e/example/lib/data/permission_handler.dart#L70) to see a device on android 11.

> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(SecurityException, java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10574, packageName = com.example.app, attributionTag = null, token = android.os.BinderProxy@d6be1ce, next = null }: GattService registerScanner, Cause: null, Stacktrace: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10574, packageName = com.example.app, attributionTag = null, token = android.os.BinderProxy@d6be1ce, next = null }: GattService registerScanner

I get the same error on android 14 with your example app. Seems like the manifest permission is not working for bluetooth (anymore?). 

One has to use a third party package to do permission work. Maybe you should add this to your docs or `README.MD`. Or did I overread :exploding_head: ?

Thanks for your advice! :pray:

**Comment by konsultaner** [comment]
> @konsultaner is example app working fine for you ?

The example app shows the same error.

![WhatsApp Image 2024-08-07 at 13 11 32](https://github.com/user-attachments/assets/66d4ef65-1e90-44d3-85fa-b2b585062b9f)

**Comment by konsultaner** [comment]
I have an idea. could it be the case that sending a '\0' for message termination might cause the issue? I'm sending a zero terminated string in 20byte chunks. In that screenshot behind the read I see the last chunk:

```shell
"tes0903co2":-1}\0
```

**Comment by rohitsangwan01** [comment]
@konsultaner yes we have to ask bluetooth permissions using another plugin, you can use [this](https://github.com/Navideck/universal_ble/blob/main/example/lib/data/permission_handler.dart) class from our example app for permission part

**Comment by rohitsangwan01** [comment]
> The example app shows the same error.

can you try in [NRF connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_IN) app, if you are able to subscribe to this char ?

**Comment by rohitsangwan01** [comment]
ok seems like you peripheral does not have the descriptor for that characteristic to start notification,  we will add a workaround to fix this issue

**Comment by konsultaner** [comment]
> ok seems like you peripheral does not have the descriptor for that characteristic to start notification, we will add a workaround to fix this issue

Can I fix this on the hardware side? I'm on an `Adafruit ESP32 Feather`

**Comment by rohitsangwan01** [comment]
> Can I fix this on the hardware side? I'm on an `Adafruit ESP32 Feather`

yes you can add Client Characteristic Configuration Descriptor `00002902-0000-1000-8000-00805f9b34fb` to the characteristic which you want to subscribe

**Comment by rohitsangwan01** [comment]
@konsultaner Great, btw can you try your previous code ( Without CCCD ) with this branch https://github.com/Navideck/universal_ble/pull/72

**Comment by konsultaner** [comment]
ok, I'll give it a try tomorrow :smiley: I need to release my demo first.

**Comment by konsultaner** [comment]
sorry, I had no chance to test it yet. I do not have the hardware at the moment. As soon as I get it back, I will give it a try!
